{% set name = "Morfessor" %}
{% set version = "2.0.3" %}
{% set sha256 = "95a9c012c4383749aad91817596e5a029c4195b389689f7604645aa7a82b5e96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - morfessor
    - morfessor.test

about:
  home: https://github.com/aalto-speech/morfessor
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Library for unsupervised and semi-supervised morphological segmentation'

  description: |
    Morfessor is a simple, pure Python library for conducting unsupervised and 
    semi-supervised morphological segmentation tasks.
  doc_url: http://morfessor.readthedocs.org/
  dev_url: https://github.com/aalto-speech/morfessor

extra:
  recipe-maintainers:
    - souravsingh
    - psmit
